# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Maven install
      run: mvn install
    - name: Tomcat install
      run: bash .github/scripts/install_tomcat.sh
    - name: Install webapps
      run: ls /opt/tomcat/webapps && cp target/java-web-project.war /opt/tomcat/webapps/java-web-project.war && ls /opt/tomcat/webapps
    - name: Tomcat startup
      run: ls /opt/tomcat/bin && bash /opt/tomcat/bin/catalina.sh run&
      #- name: Maven deploy with Tomcat
      # run: mvn tomcat:deploy
    - name: Test 1
      run: curl http://localhost:8080 1> /dev/null
    - name: Test root
      run: curl http://localhost:8080/java-web-project
    - name: Test 2 root
      run: curl http://localhost:8080/java-web-project/HelloWorldJSP
    - name: Test 3 root
      run: curl http://localhost:8080/java-web-project/HelloWorldNoJSP
    - name: Shutdown
      run: bash /opt/tomcat/bin/shutdown.sh
